services: 
  mysqldb:
    restart: on-failure
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=proyecto
      - MYSQL_PASSWORD=proyecto
      - MYSQL_DATABASE=proyecto_db
    ports:
      - "3307:3306"
    networks:
      - app_net
    volumes:
      - mysql-vol:/var/lib/mysql
      - ./database/database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
  
  backend:
    depends_on:
        - mysqldb
    restart: on-failure
    container_name: backend
    image: carlosmz87/proyecto_ayd1_backend
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app_net
    links:
      - mysqldb
    environment:
      - DATABASE_USER=proyecto
      - DATABASE_PASSWORD=proyecto
      - DATABASE_HOST=mysqldb
      - DATABASE_NAME=proyecto_db
      - DATABASE_PORT=3306

  frontend:
    depends_on:
      - backend
    container_name: frontend
    image: carlosmz87/proyecto_ayd1_frontend
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app_net
    links:
      - backend

networks:
  app_net:
    driver: bridge

volumes:
  mysql-vol: