services: 
  mysqldb:
    restart: on-failure
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=proyecto
      - MYSQL_PASSWORD=proyecto
      - MYSQL_DATABASE=proyecto_db
    ports:
      - "3307:3306"
    networks:
      - app_net
    volumes:
      - mysql-vol:/var/lib/mysql
      - ./database/database_init.sql:/docker-entrypoint-initdb.d/database_init.sql

networks:
  app_net:
    driver: bridge

volumes:
  mysql-vol: