FROM alpine:latest
RUN apk update
RUN apk add py3-pip
RUN apk add --no-cache python3-dev \
    && pip3 install --upgrade pip setuptools
RUN mkdir -p /usr/src/app/public
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN pip3 --no-cache-dir install -r requirements.txt
CMD [ "python3", "server.py" ]
