DELIMITER $$
CREATE PROCEDURE CrearDireccion(
    IN MUNICIPIO_ID BIGINT,
    IN LUGAR VARCHAR(500),
    OUT DIR_ID BIGINT
)
BEGIN
    INSERT INTO DIRECCION (MUNICIPIO_MUN_ID, LUGAR) VALUES (MUNICIPIO_ID, LUGAR);
    SET DIR_ID = LAST_INSERT_ID();
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE ActualizarEstadoOrden(
    IN ID_ORDEN BIGINT
)
BEGIN
	DECLARE cantidad_rechazado INT;
	DECLARE cantidad_aceptado INT;
	DECLARE cantidad_pendiente INT;
	SET cantidad_rechazado = (SELECT COUNT(do.ORDEN_ORD_ID) FROM DETALLE_ORDEN do  WHERE do.ORDEN_ORD_ID = ID_ORDEN AND do.ESTADO = 'RECHAZADO' GROUP BY do.ORDEN_ORD_ID);
	IF cantidad_rechazado > 0 THEN
		UPDATE ORDEN SET ESTADO = 'CANCELADO' WHERE ORD_ID = ID_ORDEN;
	ELSE
		SET cantidad_pendiente = (SELECT COUNT(ORDEN_ORD_ID) FROM DETALLE_ORDEN do WHERE ESTADO = 'PENDIENTE');
		IF cantidad_pendiente = 0 THEN
			UPDATE ORDEN SET ESTADO = 'RECIBIDO' WHERE ORD_ID = ID_ORDEN;			
		END IF;
	END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE AsignarPedidoRepartidor(
    IN ID_ORDEN BIGINT,
    IN USUARIO VARCHAR(250)
)
BEGIN
    IF (SELECT COUNT(O.ESTADO) FROM ORDEN O WHERE O.ESTADO = 'EN PROCESO' AND O.REPARTIDOR_REP_ID = USUARIO) = 0 THEN
        UPDATE ORDEN O
        INNER JOIN REPARTIDOR R on O.REPARTIDOR_REP_ID = R.REP_ID
        SET O.ESTADO = 'EN PROCESO'
        WHERE O.ESTADO = 'RECIBIDO' AND O.ORD_ID=ID_ORDEN AND R.USUARIO = USUARIO;
    END IF;
END $$
DELIMITER ;